### ISSUE TITLE
Unable to locate a class or view for component [form.form-input]

### ISSUE THREAD

**Issue by xtfer** [protonemedia/laravel-form-components#21]
Maybe I'm missing something obvious here, but I've installed the package and I'm still getting errors trying to load any component, e.g.`Unable to locate a class or view for component [form.form-input]`.

I thought perhaps it wasn't registering properly so I tried adding the Service Provider in app.config, but that made no difference.

**Comment by pascalbaljet** [comment]
Did you change the configuration file? What version of Laravel are you using?

**Comment by xtfer** [comment]
On review I don't think this is a problem with laravel-form-components. I'm getting the same issue with any component.

I'm using Laravel Spark on Laravel 8.10.

**Comment by vwasteels** [comment]
@xtfer did you figure this out ? I'm getting the same error...

**Comment by vwasteels** [comment]
wow... found it ..... I just did not install ...... the package !

`composer require protonemedia/laravel-form-components` solved it for me hahaha

**Comment by pascalbaljet** [comment]
Happens to the best of us! 🙃

**Comment by xtfer** [comment]
I never worked out what this was but I think it was an issue with Laravel Spark, tbh.
