### ISSUE TITLE
Remove or alter the "mt-4"

### ISSUE THREAD

**Issue by wrabit** [protonemedia/laravel-form-components#23]
Would be nice to able to control this via something like 

`<x-form-input field-class="mb-2" />`

IMO too much spacing for a compact form, better to be adjustable.

<img src="https://user-images.githubusercontent.com/5918271/96997227-a9b93480-1531-11eb-9190-185687e58de0.png" width="400">

Something like:

```
FormInput.php

        string $name,
        string $label = '',
        string $type = 'text',
        string $fieldClass = 'mt-4'
...

form-input.blade.php

        <div class="@if($type === 'hidden') hidden @else $fieldClass @endif">
```

**Comment by wrabit** [comment]
Maybe wrapper-class is more generic.

**Comment by pascalbaljet** [comment]
You can publish the Blade views and customize to your needs:
https://github.com/protonemedia/laravel-form-components#customize-the-blade-views
