### ISSUE TITLE
No help slot in Tailwind form input

### ISSUE THREAD

**Issue by wrabit** [protonemedia/laravel-form-components#24]
https://github.com/protonemedia/laravel-form-components/blob/master/resources/views/tailwind/form-input.blade.php

**Comment by pascalbaljet** [comment]
Block-level help text is a first-party Bootstrap feature, it's not included in the default Tailwind Custom Forms plugin. This package adheres mostly to the default features/demos of both frameworks. As I commented [on the other issue](https://github.com/protonemedia/laravel-form-components/issues/23#issuecomment-715350339), just publish the views and customize whatever you want.
