### ISSUE TITLE
select multiple does not handle selected attribute

### ISSUE THREAD

**Issue by vwasteels** [protonemedia/laravel-form-components#31]
Hello,

When I do this : 

```blade
@bind($model)
<x-form-select
  multiple
  name="categories[]"
  :options="App\Models\Categories::options()"
/>
@endbind($model)
```

Categories are saved, but they are not selected on page reload : no `selected` attribute on the `<option>` tags ,

am I doing it wrong ?

BTW this is my `App\Models\Categories::options()` :

```php
[
   1 => "Justice",
   2 => "Culture",
   3 => "Agriculture"
]
```

**Comment by vwasteels** [comment]
I am still stuck on this, if anyone knows how to set the "selected" attribute , that would be great :)

**Comment by pascalbaljet** [comment]
What is `$model->categories`? Is it a relationship (what kind?) or an array?

**Comment by vwasteels** [comment]
yes it is a `morphToMany` relation , 

I figured how to do it , by bypassing the model binding, not the nicest way, but it works :

```blade
<x-form-select
multiple
name="categories[]"
>
  @foreach(App\Models\Categories::options() as $id => $option)
    <option
    value="{{ $id }}"
    @if($model->categories->contains($id))
      selected
    @endif
    >{{ $option }}</option>
  @endforeach
</x-form-select>

```

**Comment by pascalbaljet** [comment]
Maybe we can add a `relation` attribute to handle this use-case.

```blade
@bind($model)
    <x-form-select multiple relation
        name="categories[]"
        :options="App\Models\Categories::options()" />
@endbind($model)

**Comment by pascalbaljet** [comment]
WIP: https://github.com/protonemedia/laravel-form-components/pull/34/files

**Comment by pascalbaljet** [comment]
This has been added in 2.5.0:
https://github.com/protonemedia/laravel-form-components#using-eloquent-relationships
