### ISSUE TITLE
Pass class to child component

### ISSUE THREAD

**Issue by temosis** [protonemedia/laravel-form-components#32]
Is there any way to pass class to the label inside `<x-form-input>`

**Comment by pascalbaljet** [comment]
You should [publish the Blade views](https://github.com/protonemedia/laravel-form-components#customize-the-blade-views) and then you could use the `$attributes` variable inside the `form-input` view. You don't have to touch the `form-label` view.

Try this in your form:

```blade
<x-form-input label-class="text-xl">
```

And then modify the `form-input` view so passes the `label-class` attribute to the `form-label` component:

```blade
<x-form-label :label="$label" :class="$attributes['label-class'] ?? null" />
```

**Comment by temosis** [comment]
That works as intended. I guess i miss understood how component data is shared.
