### ISSUE TITLE
Is there an option to wire:ignore?

### ISSUE THREAD

**Issue by ioanschmitt** [protonemedia/laravel-form-components#35]
Hi, I just have a question, is there a way to use wire:ignore with the package, I couldn't find an answer so I'm asking it here 😃

**Comment by pascalbaljet** [comment]
Adding `wire:ignore` tells Livewire to ignore changes inside that element, right? Is there anything in particular not working with this package when you're using `wire:ignore`?

```blade
<x-form wire:submit.prevent="submit">
    @wire
        <x-form-input name="name" />
        <x-form-input name="email" />

        <div wire:ignore>
            <div class="external-library-component"></div>
        </div>
    @endwire

    <x-form-submit>Save Contact</x-form-submit>
</form>
```

**Comment by ioanschmitt** [comment]
Oh, no everything works fine. I did an mistake somewhere else, that's because it was not working. Forgot to close the issue. Thanks for this great package!
