### ISSUE TITLE
checked checkbox on edit won't uncheck (boolean)

### ISSUE THREAD

**Issue by musixite** [protonemedia/laravel-form-components#37]
Field: attention_grabber (boolean)

When creating an object, the value is set properly (1 if checked, 0 if unchecked)
When updating an object, if attention_grabber is unchecked, then the value updates correctly if checked (ie 1)
However when updating an object, if attention_grabber is checked, the value stays checked even if unchecked.

I tried changing the field to an input value (and set manually to 0 or 1) and it works well.

I assume there is something going on with my code but I don't know what's wrong (very basic):
```
// doesn't work on update to uncheck
<x-form-checkbox name="attention_grabber" label="Attention Grabber" />

// works on any situation
<x-form-input name="attention_grabber" label="Attention Grabber" />

// also works
<x-form-group name="attention_grabber" label="Attention Grabber" inline>
  <x-form-radio name="attention_grabber" value="1" label="Yes" />
  <x-form-radio name="attention_grabber" value="0" label="No" />
</x-form-group>
```

**Comment by pascalbaljet** [comment]
If you're using the checkbox, you need to use the `boolean` method of the `Request` instance:

```php
$model->update([
    'attention_grabber' => $request->boolean('attention_grabber')
]);
```

See also: https://laravel.com/docs/master/requests#retrieving-boolean-input-values
