### ISSUE TITLE
Tailwind custom-forms still required?

### ISSUE THREAD

**Issue by ClementN** [protonemedia/laravel-form-components#38]
Hello,

In the README.md file it reads 
```Make sure the Tailwind plugin is installed and added to your tailwind.config.js``` 

Is this the case when Tailwind v2 is used, as Tailwind v2 replaced custom-forms with its included forms. 

Thank you,

**Comment by pascalbaljet** [comment]
You're absolutely right, v2 requires another plugin. I've updated the README!
