### ISSUE TITLE
Problem when using livewire together with labels

### ISSUE THREAD

**Issue by stmn** [protonemedia/laravel-form-components#39]
Hello,

It is because of randomly generated id - livewire can't properly match dom elements or something like this. It result in lost focus on input.

I suggest to fix examples in readme and/or add information that livewire require to pass id. 
Alternatively we could disable random id when using livewire.

**Comment by pascalbaljet** [comment]
I just tagged v2.5.1, which generates the ID based on the `name` attribute instead of randomly.
https://github.com/protonemedia/laravel-form-components/releases/tag/2.5.1
