### ISSUE TITLE
Checkboxes and Radios broken after 2.5.1

### ISSUE THREAD

**Issue by therajumandapati** [protonemedia/laravel-form-components#42]
After 2.5.1, it seems that Checkboxes and Radio buttons are broken when used in a Grouped setting. This is because the ID was previously being dynamically generated which was replaced to simply use the name attribute. 

As the `id` attribute is the same for multiple inputs targeting the same option, the value will not change between different options. 

Please see attached screenshot comparing this with 2.5.1 and 2.1.1:

2.5.1 (broken):
![image](https://user-images.githubusercontent.com/5555261/103557583-68ea7e00-4ed9-11eb-8cfd-21b5e97ccd52.png)

2.1.1 (working):
![image](https://user-images.githubusercontent.com/5555261/103557368-15783000-4ed9-11eb-9621-2c64996410d7.png)

**Comment by therajumandapati** [comment]
This commit https://github.com/protonemedia/laravel-form-components/commit/2688847ee4f5647739205283341fbcff53cf1209 seems to be what started this.

**Comment by pascalbaljet** [comment]
I just tagged v2.5.2 which should solve this :)

**Comment by therajumandapati** [comment]
@pascalbaljet Seems to be working, thanks for the quick fix.
