### ISSUE TITLE
Question: How to Add a empty Field to Select

### ISSUE THREAD

**Issue by chellmann** [protonemedia/laravel-form-components#44]
Hi there,

thank you very much for your great Work on this Package.

It would be great if you could point me to the right direction.

I would like to use the Select field with an empty entry on top (value="") with a Label "please choose a option", for example in a Livewire-Form for searching a table.
Shure, i could use `array_merge([''=>'please choose'],$values);` in the `:options=` prop, but maybe there is a neater way.

Thanks a lot,

Conrad

**Comment by pascalbaljet** [comment]
This now supported in v3.2.0 :)
