### ISSUE TITLE
Bootstrap 5 support ?

### ISSUE THREAD

**Issue by mustafa-online** [protonemedia/laravel-form-components#50]
Hi there, does this package support **Bootstrap 5** ?
I wanna use it with a new admin panel that i'm going to build.

**Comment by pascalbaljet** [comment]
I think I’ll add support once Bootstrap 5 is out of beta.

**Comment by kb6673** [comment]
There isn't really much work to do in the meantime.

I just published the bootstrap-4 assets and it pretty much worked.

I did modify mine slightly to support BS5 floating labels.

![image](https://user-images.githubusercontent.com/1001484/117444835-e7136b80-af31-11eb-9b65-9f535b79218b.png)

```
 <div class="form-floating">
            <x-form-input name="first_name" label="First Name *" placeholder="First Name *" required/>
 </div>
```

I'll see if I can do a PR to support BS5 to help others

**Comment by rabol** [comment]
It's out of beta now :)
