### ISSUE TITLE
support for Livewire deferred updating?

### ISSUE THREAD

**Issue by wivaku** [protonemedia/laravel-form-components#57]
With Livewire it is possible to [defer updating](https://laravel-livewire.com/docs/2.x/properties#deferred-updating).

E.g. 
```
<input type="text" wire:model.defer="query">
```

Would be great if this can be supported in laravel-form-components.
E.g. 
```
<x-form-input name="query" defer />
```

BTW. similar (but lower prio) request for lazy / debounce.

**Comment by o4itea** [comment]
It's alreay support livewire modifires, please read the documentation

[https://github.com/protonemedia/laravel-form-components#laravel-livewire](https://github.com/protonemedia/laravel-form-components#laravel-livewire)

**Comment by wivaku** [comment]
Thanks, it seems I had not read the documentation carefully enough.
