### ISSUE TITLE
bind issue

### ISSUE THREAD

**Issue by junwoo-nichibo** [protonemedia/laravel-form-components#58]
when using bind with the x-form-input , doesn't show the correct value, especially the value is 0. I guess the issue is bound value.

```
$default = $this->getBoundValue($bind, $name) ?: $default;

to

$default = $this->getBoundValue($bind, $name) ?? $default;

```
in \src\Components\HandlesDefaultAndOldValue.php.

**Comment by pascalbaljet** [comment]
Fixed in v3.1.0.
