### ISSUE TITLE
Select (tailwind 2) doesn't display first option - malformed html

### ISSUE THREAD

**Issue by jim-whiteside** [protonemedia/laravel-form-components#60]
in `resources/views/tailwind-2/form-select.blade.php` - the main `<select>` tag is not properly closed, which means that the first option is not displayed, and the resulting rendered html is invalid.

Solution: Add closing `>` e.g. on line 21

```
diff --git resources/views/vendor/form-components/tailwind-2/form-select.blade.php resources/views/vendor/form-components/tailwind-2/form-select.blade.php
index ba7abfe..704d86d 100644
--- resources/views/vendor/form-components/tailwind-2/form-select.blade.php
+++ resources/views/vendor/form-components/tailwind-2/form-select.blade.php
@@ -18,6 +18,7 @@
             @if($multiple)
                 multiple
             @endif
+        >
 
             @forelse($options as $key => $option)
                 <option value="{{ $key }}" @if($isSelected($key)) selected="selected" @endif>
```

**Comment by pascalbaljet** [comment]
Did you use the latest version of v2? It seems to close after the class attribute code.

https://github.com/protonemedia/laravel-form-components/blob/master/resources/views/tailwind-2/form-select.blade.php#L18
