### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Augen2203** [protonemedia/laravel-form-components#69]
Hi, thanks for your package.

I decided to use it in my project, and immediately saw that the rendering speed (decreased) and the amount of memory usage increased significantly (I display this in the screenshot).

I wanted to ask you if this is due to the package or to the fact that the blade components themselves are working slowly, as previously there was little experience with them. Thanks to.
<img width="440" alt="Снимок экрана 2021-11-15 в 14 14 35" src="https://user-images.githubusercontent.com/59070939/141780739-ee387676-b6b8-444e-bf7b-9353a258b2d6.png">

**Comment by mrl22** [comment]
I think this may be down to something you are doing. I have been using laravel-form-components for a while and thought I would compare with and without as I was curious about your question.

Based on an edit page I made to change some input boxes and upload a PDF. 1 input, 2 text areas and 2 upload file inputs.

Without (normal HTML inputs)- 5MB Ram and 33.68ms
With components - 5MB 66.23ms

So it is slightly slower which is expected, but not by much.

**Comment by pascalbaljet** [comment]
Could you share a code example of a slow view?
