### ISSUE TITLE
Add margin end on radio button on bootstrap 5

### ISSUE THREAD

**Issue by abdasis** [protonemedia/laravel-form-components#86]
![Cuplikan layar 2022-02-06 075406](https://user-images.githubusercontent.com/34927165/152664065-c1a8ff19-73b0-461d-a4c4-af4765a96855.png)

I found something wrong with the radio button in bootstrap 5, the component was overwritten in inline display

**Comment by masakik** [comment]
I found this using bootstrap 4 too. As stated on readme, the style 'inline-space' is defined in form.blade.php and applied in form-group. It is not effective not sure why. But bootstrap docs says to use 'form-check-inline' class. I'm wondering why not to use this class here.

**Comment by masakik** [comment]
OK, using x-form to wrap other components, the style is included and solves this issue. But why not to use bootstrap classes instead of custom css?
